### ISSUE TITLE
Clean up stack traces

### ISSUE THREAD

**Issue by powerdude** [TestStack/TestStack.BDDfy#188]
Hello,

Is there a way to catch and clean up stack traces to remove "library" information.  For instance, in the following stack trace, I don't need to see unit testing framework information("at Microsoft....") or BDDfy:

Story: Account holder withdraws cash
	As an Account Holder
	I want to withdraw cash from an ATM
	So that I can get money when the bank is closed

Scenario: Account has insufficient fund
	Given the account balance is $10                            [Passed] 
	  And the card is valid                                     [Passed] 
	  And the machine contains enough money                     [Passed] 
	When the account holder requests $20                        [Passed] 
	Then the atm should not dispense any money                  [Failed] [Assert.AreEqual failed. Expected:<0>. Actual:<1>.] [Details at 1 below]
	  And the atm should say there are insufficient funds       [Passed] 
	  And the account balance should be 10                      [Passed] 
	  And the card should be returned                           [Passed] 

Exceptions:
  1. Assert.AreEqual failed. Expected:<0>. Actual:<1>.
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFailure(String assertionName, String message)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[T](T expected, T actual, String message, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[T](T expected, T actual)
   at SampleTests.AccountHasInsufficientFund.ThenTheAtmShouldNotDispenseAnyMoney() in D:\code\me\Main\SampleTests\Class1.cs:line 135

Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.AreEqual failed. Expected:<0>. Actual:<1>. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFailure(String assertionName, String message)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[T](T expected, T actual, String message, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.AreEqual[T](T expected, T actual)
   at RedDragon.BeastMode.UI.Tests.AccountHasInsufficientFund.ThenTheAtmShouldNotDispenseAnyMoney() in D:\code\me\Main\SampleTests\Class1.cs:line 135
   at TestStack.BDDfy.Processors.ExceptionProcessor.Process(Story story)
   at TestStack.BDDfy.Engine.Run()
   at TestStack.BDDfy.BDDfyExtensions.BDDfy(Object testObject, String scenarioTitle)
   at SampleTests.AccountHolderWithdrawsCash.AccountHasInsufficientFund() in D:\code\me\Main\SampleTests\Class1.cs:line 170

**Comment by JakeGinnivan** [comment]
This is not possible. The exception is thrown inside a test method which BDDfy is calling. 

The Microsoft.TestTools bit is your unit test assertion framework.

As a suggestion, try https://github.com/shouldly/shouldly - it is a way better assertion framework than the stuff built into mstest. Also xUnit is a better unit test framework.

**Comment by powerdude** [comment]
Yes, it is thrown inside a test method, but I'm guessing you're catching the exception and printing the stack trace.  A regex could be ran on the stacktrace to remove extra lines before you print the stack trace to console or a file.

**Comment by MehdiK** [comment]
You're right @powerdude. I think this can be cleaned up to only show the appropriate call stack. 

It would be lovely if you could send a PR to deal with this. Just don't forget that your regex (or cleanup code) should be able to deal with all major testing frameworks and also test runners: think MSTest, nUnit, xUnit and then nUnit and xUnit runners plus R# & TD.Net.

Thanks.

**Comment by JakeGinnivan** [comment]
Good point guys.

It also needs to work with debug and release builds of BDDfy (debug includes path info and line numbers).
