### ISSUE TITLE
Make BDDfy compatible with xUnit.dnx

### ISSUE THREAD

**Issue by nokinger** [TestStack/TestStack.BDDfy#216]
When try to run a simple xUnit.dnx Test with BDDfy, i got the following exception in Test explorer: 

```
Test Name:	DnxTestClass.DnxTest
Test FullName:	XUnit.Test.dnx.DnxTestClass.DnxTest
Test Source:	D:\xUnit.Tests\xUnit.Test.dnx\DnxUnitTest.cs : line 14
Test Outcome:	Failed
Test Duration:	0:00:00,021

Result StackTrace:	
at TestStack.BDDfy.StoryAttributeMetadataScanner.<>c__DisplayClass1.<GetCandidateStory>b__0(StackFrame f)
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at TestStack.BDDfy.StoryAttributeMetadataScanner.GetCandidateStory(Object testObject, Type explicitStoryType)
   at TestStack.BDDfy.StoryAttributeMetadataScanner.GetStoryMetadata(Object testObject, Type explicityStoryType)
   at TestStack.BDDfy.StoryAttributeMetadataScanner.Scan(Object testObject, Type explicitStoryType)
   at TestStack.BDDfy.DefaultScanner.Scan()
   at TestStack.BDDfy.Engine.Run()
   at TestStack.BDDfy.BDDfyExtensions.BDDfy(Object testObject, String scenarioTitle)
   at XUnit.Test.dnx.DnxTestClass.DnxTest() in D:\xUnit.Tests\xUnit.Test.dnx\DnxUnitTest.cs:line 15
Result Message:	Object reference not set to an instance of an object.
```

**Comment by wmekal** [comment]
Hello, could anyone please look on my pull-request and accept/refuse it?

It might help people wanting to use BDDfy with dnx.

**Comment by nokinger** [comment]
Hi @wmekal, 
sorry for the late answer, your changes are working. 
But i am confused, becaused the BDDfy reports will be not displayed in the xUnit Runner.
With a normal (not dnx) Version all is working fine. Maybe this must be addressed to the xUnit.dnx repo i'am not sure how are the right recipient!?

**Comment by JakeGinnivan** [comment]
DNX doesn't support stacktraces at the moment as far as I know, this probably is the source of the issue.

The change means that you cannot attribute your class with the [Story] attribute.

**Comment by JakeGinnivan** [comment]
I am happy enough with the change, I have been travelling a fair bit and am trying to get back on top of things. I will merge/release once I finish some other tasks

**Comment by wmekal** [comment]
@JakeGinnivan @nokinger Thanks for reviewing and checking it!

**Comment by tmaierhofer** [comment]
Any news on this?

**Comment by JakeGinnivan** [comment]
W are shipping proper netstandard support soon, hopefully this should fix the issue properly.
