### ISSUE TITLE
Additional methods in fluent syntax causes exception 'variable referenced from scope ... but it is not defined'

### ISSUE THREAD

**Issue by develorem** [TestStack/TestStack.BDDfy#251]
System: Nunit test, resharper test runner, .Net 4.6, BDDfy version 4.1.2

Example code:

```
this.Given(x => x.GivenTheSiteCoverageService())
       .And(x => x.GivenTheFirstAerialJobSite().WithCoverage(80m).OverSite(FirstSite))
       ....

```
Effectively, putting the additional methods "WithCoverage" and "OverSite" causes BDDFY to fail with exception:

An exception of type 'System.InvalidOperationException' occurred in System.Core.dll but was not handled in user code

Additional information: variable 'x' of type '<snip>' referenced from scope '', but it is not defined

Removing the fluent extensions I created for my types allows it to work.
But the alternative of complex unreadable constructors for all my permutations is wrong (shouldn't have to change the object under test). Is there a way to achieve what I'm trying to achieve here?

**Comment by develorem** [comment]
Sorry, stack trace would have been helpful:

   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at TestStack.BDDfy.ExpressionExtensions.ArgumentExtractorVisitor.GetValue(Expression a)
   at TestStack.BDDfy.ExpressionExtensions.ArgumentExtractorVisitor.ExtractStepArgument(Expression a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at TestStack.BDDfy.ExpressionExtensions.ArgumentExtractorVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at TestStack.BDDfy.ExpressionExtensions.ExtractArguments[T](LambdaExpression expression, T value)
   at TestStack.BDDfy.FluentScanner`1.AddStep(Action`1 action, LambdaExpression stepAction, String stepTextTemplate, Boolean includeInputsInStepTitle, Boolean reports, ExecutionOrder executionOrder, Boolean asserts, String stepPrefix)
   at TestStack.BDDfy.FluentStepBuilder`1.And(Expression`1 step)

**Comment by develorem** [comment]
I suspect the offending code is the fact that the ExpressionExtensions.ArgumentExtractorVisitor.GetValue() method assumes a Func<object> when in fact the first call in my method chain returns an object as well.

**Comment by SonOfSardaar** [comment]
this should be addressed by #307 . If it does not , then please re-open it with good example that can explain setup and expectation better.
